import cv2
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Load the ROI overlay image generated by main_mech.py
overlay = cv2.imread('mechanical_rois_overlay.png')
if overlay is None:
    print("ERROR: Could not find mechanical_rois_overlay.png")
else:
    # Check the image
    print(f"Overlay shape: {overlay.shape}")
    print(f"Overlay dtypes: {overlay.dtype}")
    
    # Check if red contour is visible (ROI outline)
    red_channel = overlay[:,:,2]  # B,G,R in OpenCV
    red_pixels = np.count_nonzero(red_channel > 200)
    print(f"Red pixels (ROI outline): {red_pixels}")
    
    # Load original to compare
    original = cv2.imread('debug_organoid_original.png', 0)
    print(f"Original shape: {original.shape}, max brightness: {original.max()}, mean: {original.mean():.1f}")
    
    # Load the mask
    mask = cv2.imread('debug_organoid_mask.png', 0)
    print(f"Mask shape: {mask.shape}, non-zero pixels: {np.count_nonzero(mask)}")
    
    # Create a custom visualization
    fig, axes = plt.subplots(2, 2, figsize=(12, 12))
    
    # Original image
    axes[0,0].imshow(original, cmap='gray')
    axes[0,0].set_title('Original Reference Image')
    axes[0,0].axis('off')
    
    # High-pass filter
    highpass = cv2.imread('debug_organoid_highpass.png', 0)
    axes[0,1].imshow(highpass, cmap='gray')
    axes[0,1].set_title('High-Pass Filtered (Border Emphasis)')
    axes[0,1].axis('off')
    
    # Mask overlay
    overlay_mask = original.copy()
    overlay_mask[mask > 0] = 255
    axes[1,0].imshow(overlay_mask, cmap='gray')
    axes[1,0].set_title('Mask Overlay on Original')
    axes[1,0].axis('off')
    
    # ROI overlay from main_mech
    overlay_rgb = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)
    axes[1,1].imshow(overlay_rgb)
    axes[1,1].set_title('ROI Overlay from main_mech.py')
    axes[1,1].axis('off')
    
    plt.tight_layout()
    plt.savefig('debug_visualization.png', dpi=100, bbox_inches='tight')
    print("Saved visualization to debug_visualization.png")

